import URLS from './urls';

const ICONS = {
    loginBackground: `${URLS.iconBaseURL}/background_image.png`,
    logo: `${URLS.iconBaseURL}/logo.png`,
    landingPageLogo: `${URLS.iconBaseURL}/landing-page-logo.png`,
    mainLayoutLogo: `${URLS.iconBaseURL}/savy-broker-logo--white.svg`,
    mainLayoutResponsiveLogo: `${URLS.iconBaseURL}/savy-broker-face-logo.svg`,
    mainLayoutFaceLogo: `${URLS.iconBaseURL}/savy-broker-face-logo--gray.svg`,
    whitePlusIcon: `${URLS.iconBaseURL}/plus-circle-white.svg`,
    bluePlusIcon: `${URLS.iconBaseURL}/plus-circle.svg`,
    blueMinusIcon: `${URLS.iconBaseURL}/minus-icon.svg`,
    whiteMinusIcon: `${URLS.iconBaseURL}/minus-icon--white.svg`,
    homeSmartIcon: `${URLS.iconBaseURL}/home-smart.svg`,
    glassHourIcon: `${URLS.iconBaseURL}/glass-hour.svg`,
    cashFlowIcon: `${URLS.iconBaseURL}/cash-flow.svg`,
    financeIcon: `${URLS.iconBaseURL}/finance-cue.svg`,
    cyclonesIcon: `${URLS.iconBaseURL}/cyclones.svg`,
    mortgageIcon: `${URLS.iconBaseURL}/common-mortgage.svg`,
    firstGroupedIcons: `${URLS.iconBaseURL}/landing-gr-icons-1.svg`,
    secondGroupedIcons: `${URLS.iconBaseURL}/landing-gr-icons-2.svg`,
    thirdGroupedIcons: `${URLS.iconBaseURL}/landing-gr-icons-3.svg`,
    forthGroupedIcons: `${URLS.iconBaseURL}/landing-gr-icons-4.svg`,
    leftArrow: `${URLS.iconBaseURL}/left-arrow.svg`,
    thunderIcon: `${URLS.iconBaseURL}/thunder.svg`,
    rightArrow: `${URLS.iconBaseURL}/right-arrow.svg`,
    profileIcon: `${URLS.iconBaseURL}/profile.svg`,
    emailIcon: `${URLS.iconBaseURL}/mail.svg`,
    phoneIcon: `${URLS.iconBaseURL}/phone.svg`,
    statusIcon: `${URLS.iconBaseURL}/status.svg`,
    creditScoreIcon: `${URLS.iconBaseURL}/creditScore.svg`,
    locationIcon: `${URLS.iconBaseURL}/location.svg`,
    addPropertyIcon: `${URLS.iconBaseURL}/add-property.svg`,
    binIcon: `${URLS.iconBaseURL}/bin.svg`,
    uploadcon: `${URLS.iconBaseURL}/upload.svg`,
    valueIcon: `${URLS.iconBaseURL}/value.svg`,
    valueGrayIcon: `${URLS.iconBaseURL}/value--gray.svg`,
    originationDateIcon: `${URLS.iconBaseURL}/origination.svg`,
    mortaggeLengthIcon: `${URLS.iconBaseURL}/length.svg`,
    mortaggeGrayLengthIcon: `${URLS.iconBaseURL}/length--gray.svg`,
    loanAmountIcon: `${URLS.iconBaseURL}/loanAmount.svg`,
    loanAmountGrayIcon: `${URLS.iconBaseURL}/loanAmount--gray.svg`,
    interestRateIcon: `${URLS.iconBaseURL}/interestRate.svg`,
    interestGrayRateIcon: `${URLS.iconBaseURL}/interestRate--gray.svg`,
    monthlyPaymentIcon: `${URLS.iconBaseURL}/repayment.svg`,
    closeIcon: `${URLS.iconBaseURL}/cross.svg`,
    arrowUp: `${URLS.iconBaseURL}/arrowUp.svg`,
    arrowDown: `${URLS.iconBaseURL}/arrowDown.svg`,
    occpancy: `${URLS.iconBaseURL}/occupancy.svg`,
    porpertyType: `${URLS.iconBaseURL}/propertyType.svg`,
    spinner: `${URLS.iconBaseURL}/spinner.svg`,
    megaphone: `${URLS.iconBaseURL}/megaphone.svg`,
    calendarIcon: `${URLS.iconBaseURL}/calendar.svg`,
    clockIcon: `${URLS.iconBaseURL}/clock.svg`,
    recurranceIcon: `${URLS.iconBaseURL}/recurrance.svg`,
    archiveIcon: `${URLS.iconBaseURL}/archive.svg`,
    notFound: `${URLS.iconBaseURL}/404.svg`,
    licenseIcon: `${URLS.iconBaseURL}/lisence.svg`,
    shieldIcon: `${URLS.iconBaseURL}/shield.svg`,
    pricingIcon: `${URLS.iconBaseURL}/pricing.svg`,
    checkIcon: `${URLS.iconBaseURL}/check.svg`,
};

export default ICONS;
